name: Check latest Lens version

on:
  schedule:
    - cron: '10 08 */15 * *'
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.GA_PAT }}
      - name: Get the latest version of Lens
        run: |
          curl -s https://lens-binaries.s3.amazonaws.com/ide/latest-mac.yml |\
            grep -o "version:.*-latest" | grep -oP "(\d+(:?\.\d+)+)" |\
            head -n 1 > version
          export LENS_VERSION=$(cat ./Casks/openlens-version)
          echo "LENS_VERSION=$LENS_VERSION" >> $GITHUB_ENV
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Version updated to: ${{ env.LENS_VERSION }}'
